server:
  port: 9150

localeTag: "ru-Ru"

telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://7307-178-121-14-90.eu.ngrok.io"
  bot-name: "VangaSuperBot"
  bot-token: "5654028054:AAE5cyy5QcqXzhlh3_bspWhxk93oi3194mA"
#  proxyType: "SOCKSS"
#  proxyHost: "localhost"
#  proxyPort: "9150"

spring:
  data:
    mongodb:
      uri: "mongodb+srv://admin:qwer1234@cluster0.6ugbkde.mongodb.net/vangabot_mongoDB?retryWrites=true&w=majority"