server:
  port: 9150
localeTag: "ru-Ru"
telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://c6b5-178-121-33-207.eu.ngrok.io"
  bot-name: "VangaSuperBot"
  bot-token: "5654028054:AAE5cyy5QcqXzhlh3_bspWhxk93oi3194mA"
#  proxyType: "SOCKSS"
#  proxyHost: "localhost"
#  proxyPort: "9150"